### ISSUE TITLE
Keyboard issue on certain Android devices (6.x seems to be affected often)

### ISSUE THREAD

**Issue by avenir941** [nerone-github/WebViewAuto#5]
Hi, I have a ford sync3. When I connect the Nubia Z11miniS , I get the result:
![1514566463-picsay](https://user-images.githubusercontent.com/35039157/34493925-ee652188-f00f-11e7-93d7-d35a6f53e9c3.png)
![1514566511-picsay](https://user-images.githubusercontent.com/35039157/34493942-fac6dbd8-f00f-11e7-913c-1196a0726050.png)

I tried to connect Samsung S5 mini, everything works fine.
What could be the reason?

**Comment by nerone-github** [comment]
Hi, could you post the info of the Android version used in that Nubia?

**Comment by avenir941** [comment]
6.0.1
On samsung is also 6.0.1 ...

**Comment by nerone-github** [comment]
Currently i have no idea, since i dont have a hardware which causes that error for me. 

Maybe try to debug yourself using the android auto head unit emulator with your Nubia and tinker with some settings in the sourcecode (e.g. margins)

**Comment by petous22** [comment]
I have same problem with Asus Zenfone 2, Android 6.0.1 with Seat Leon facelift 2017 8" MIB2 Std.

**Comment by nerone-github** [comment]
Yea basically i need your help then. I can't find it out since my devices do not cause this error. Please compile from source and debug with the Head Unit Emulator if you can find something out.. It must be some thing related to the Resolution or ROM i guess. If the error happens with the Head Unit Emulator we can narrow it down to be a phone problem. I don't think the car causes the issue anyway

**Comment by petous22** [comment]
![2](https://user-images.githubusercontent.com/35193004/34654846-69e750c0-f401-11e7-9c8e-3300a1cb1e3f.JPG)
It is the same in Head Unit Emulator: 
![1](https://user-images.githubusercontent.com/35193004/34654845-6547da76-f401-11e7-8154-b1e37ff8e24e.JPG)

**Comment by petous22** [comment]
May be problem with old API in Zenfone?

**Comment by petous22** [comment]
Why don't you use google keyboard like other application (waze or youtube apk from Kumar)?

![4](https://user-images.githubusercontent.com/35193004/34655037-6002b7d6-f404-11e7-9a99-ea79753c4530.JPG)

**Comment by nerone-github** [comment]
But why does it work on Samsung then it has the same Api level ;/ Do you have all updates from Playstore for example the latest Play Services apk? (For Appcompat)? Maybe its worth a try tonchange AppcompatButton to the regular Button class.

 don't use the Google keyboard because it is not customizable enough:

- No multilingual support (i need to type in other languages than english too at the same time)
- No quick taps for www .com http etc.
- No upper/lower case
- I don't like the api of it.. Kinda complex and search focussed. But if you want to try create a second keyboards button in the top row, implement the keyboard and show me ;) (pull request)

**Comment by petous22** [comment]
I have Play Services 11.9.51, official last version from Playstore.

**Comment by pippo45454** [comment]
Hi, i have the same problem with my LG g3 and sync 3 with 8 inch .
I have Android 6.0 and Play Services 11.9.51.
Do you have any solution?Best regards

**Comment by pippo45454** [comment]
my display...
![image](https://user-images.githubusercontent.com/35233168/34684023-12ba6f14-f4a4-11e7-9017-bdc86545129b.jpg)

**Comment by nerone-github** [comment]
Could you please try this apk? 

https://github.com/nerone-github/WebViewAuto/blob/master/apk/webviewauto-test1.apk

It uses Button instead of AppCompatButton

**Comment by pippo45454** [comment]
Thanks Nerone,
I'll try the application tomorrow and I'll let you know something.
Thanks for your help. 
Bye

**Comment by pippo45454** [comment]
Hello,

I tried again with the new files but the problem remains.

**Comment by nerone-github** [comment]
i am working on a completely new keyboard. will commit it later. It will be much better and html5 based :)

**Comment by pippo45454** [comment]
Thank a lot Nerone.
Bye

**Comment by nerone-github** [comment]
Hey all. Please try the new apk. It contains the html5 based UI which i have announced. This should solve most device-specific problems. If still problems occur please create new issues.

**Comment by petous22** [comment]
Thank a lot. New version of keyboard  fully functional, but there is little problem with small button on upper toolbar. Badly knocks in the small buttons.

**Comment by nerone-github** [comment]
sorry i did not understand. please create a new issue with explanation ;)
